### PR TITLE
This margin was causing the menu to be slightly misaligned. 

### PR DESCRIPTION
**Pull request by halfnibble**

### CODE REVIEW

**Comment by halfnibble** [comment]
This should fix it.

**Comment by RocketBrain** [comment]
Nice. I also noticed that the twitter page needs that _target in the link.
When it is clicked, it does not go to a separate page.

**Comment by RocketBrain** [comment]
Both Twitter and FB icons.

**Comment by halfnibble** [comment]
Sweet. I'll let you fix that one.
:)

**Comment by RocketBrain** [comment]
I'll commit it right now, then we'll just have to get it on the server.

**Pull request merged**
